Osx_image: B-BFA87109EB12
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/ColorThiefSwift.xcworkspace -scheme ColorThiefSwift-Example -sdk iphonesimulator10.2 -destination 'id=E40727B3-41FB-4D6E-B4CB-BFA87109EB12,platform=iOS Simulator,name=iPhone 7,OS=10.2' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
